[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."check-feed"]
  included_files = ["tracked-updates.json"]
  schedule = "0 14 * * *" # runs at 2pm UTC daily